### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by iancrossfield** [LucaMalavolta/SLOPpy#1]
The link to Sicilia et al. (2022) is broken - presumably it should link to https://ui.adsabs.harvard.edu/abs/2022arXiv220813045S

Exciting work, and thanks for making it available to the community.  I'm looking forward to trying it out.

**Comment by LucaMalavolta** [comment]
Thank you very much, the first link goes directly to the A&A page, which is not yet indexed in ADS!
Cheers,
Luca
